Use secure gRPC api's instead of HTTP api's, use discovery, clean up codebase
TheThingsNetwork/node-app-sdk pull request #64
Opened 2017-07-20 07:56 UTC by romeovs

This PR:

- Replaces the HTTP API by the gRPC API for the handler
- Uses discovery to discover the correct handler based on app ID, instead of using black magic for finding out regions
- Rewrites the codebase to be type-checked with flow type and linted like the rest of the TTN codebase
- Uses JSDoc in tandem with `documentation.js` to document the codebase
- Matches the `go-app-sdk` api better

2017-07-20 07:58 UTC, romeovs commented
Currently, there's something wrong with the gRPC client and it won't connect to `discovery.thethings.network:1900` for instance, failing with a:

```
9356:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown
```

I think this is caused by the server only supporting `TLSv1.x` and the gRPC client wanting to connect using `SSLv3` but I can't reproduce it locally. Maybe @htdvisser can have a look?

2017-07-24 09:26 UTC, johanstokking commented
Let's not merge it until that issue gets fixed.

I don't know if we should support SSLv3 though. This issue doesn't happen with other endpoints (e.g. Handler)?

2017-08-18 09:38 UTC, johanstokking commented
@romeovs 

- is Hylke's cipher suite update a fix? Travis doesn't seem to swallow it yet
- do we need SSLv3 on Discovery to make this work?
- why is TLS with the Handler working but not with Discovery?

2017-08-18 09:43 UTC, htdvisser commented
- I'm still making some changes in the public discovery server to make it support it
- We don't need SSLv3
- Because the Handler was using ECDSA certificates, while our Let'sEncrypt certificates are RSA

2017-08-23 12:06 UTC, johanstokking commented
Please reopen when tests pass

2017-08-30 14:07 UTC, romeovs commented
The tests are fixed!

2017-08-30 15:50 UTC, johanstokking commented
@romeovs still blocked?

2017-08-30 18:28 UTC, romeovs commented
@johanstokking it should be okay. It's just waiting for a review :)

2017-08-31 11:16 UTC, johanstokking requested changes

2017-08-31 11:16 UTC, johanstokking commented on .make/license.make
> +
Remove file and references

2017-08-31 11:16 UTC, johanstokking commented on README.md
> +## TODO's
Remove

2017-08-31 11:49 UTC, johanstokking approved these changes

2017-08-31 11:56 UTC, merged