feature: AccountClient (#73)
TheThingsNetwork/node-app-sdk pull request #74
Opened 2017-11-08 12:59 UTC by noerw

Adds a client for the Account Server that is exposed as `ttn.account()`.
A meaningful subset of the routes (targeting the management of applications) is implemented.

Additionally, a shorthand is added to the `ApplicationClient`: `app.getEUIs()` (#73)

2017-11-16 10:04 UTC, johanstokking commented
Thanks @noerw for the PR!

Can you fix the failing CI?

2017-11-16 12:53 UTC, noerw commented
No, not really. I didn't change anything that would affect the tests afaik.
This branch has rerun now on travis, and is not failing anymore. #75 is failing now while it was fine in the runs before.

It seems to me the test setup is broken:
- `src/handler/handler.test.js` uses `app.accessToken` from `test/stubs.js` which is not defined
- async tests don't invoke the async callback, resulting in timeouts
- looking at travis.yml: maybe there is a race condition with the docker containers?

I can't test locally b/c my docker setup is broken

2017-11-16 13:00 UTC, romeovs requested changes
Looks good. The failing test seems like a heisenbug that has nothing to do with your changes.

Fix the change requests and we're good!
Also please run:

```
make docs
```
and commit the changes `DOCUMENTATION.md`, this will update the docs with your changes.

2017-11-16 13:00 UTC, romeovs commented on src/account/account.js
> +import request from "request-promise-native"
Hmm, I'd prefer to keep out custom (fork-of-wrapper) libs. Would it be hard to change this to [`node-fetch`](https://www.npmjs.com/package/node-fetch), which implements a standardized API?

2017-11-16 13:00 UTC, romeovs commented on src/account/account.js
> +  async getAllApplications () : Promise<Array<Application>> {
There's no need to  wrap this in an `async/await` since we get a promise already from `makeRequest`.

2017-11-16 13:00 UTC, romeovs commented on src/account/account.js
> +  async getApplication (appID : string) : Promise<Application> {
Same here about the `async/await`, fix it everywhere.

2017-11-17 09:58 UTC, romeovs commented
Okay there's some type issues now. One of them is correct, the other one is caused by a bug in the upstream `flow-typed`. I've created [a PR to fix the upstream issue](https://github.com/flowtype/flow-typed/pull/1546) but you should fix the other one.

```diff
  async makeRequest (url : string, method : string = "GET", body : ?any) : Promise<any> {
    const res = await fetch(`${this.serverAddress}/${url}`, {
      method,
-     body,
+     body: JSON.stringify(body),
```

Could you write some tests? This error would've been picked up by that easily.

2017-11-18 15:17 UTC, noerw commented
Oh right, I forgot to typecheck (installed the git hooks now).
About tests: not sure how to do that. I guess I would need to write an account server (-stub), which is out of scope for me right now

2017-11-20 08:26 UTC, romeovs commented
I think a stub for the requests might be good enough, I'll write some tests today!

2017-11-20 09:40 UTC, romeovs approved these changes

2017-11-20 09:40 UTC, merged

2017-11-20 14:15 UTC, romeovs commented
The upstream error in `flow-typed` has been resolved as well (https://github.com/flowtype/flow-typed/pull/1546)!